name: ambiante_mobile
description: A map gathering all events occuring in Namur.

# Required for release
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  flutter_map: ^0.6.1+2
  # Launch urls in other apps
  url_launcher: ^5.1.2
  
# Required for development
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Command line tool used to set the app icon
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true
  assets:
  - assets/map/
  - assets/berlin.mbtiles
  - assets/map/anholt_osmbright/12/2177/
  - assets/map/anholt_osmbright/12/2178/
  - assets/map/anholt_osmbright/12/2179/
  - assets/map/anholt_osmbright/12/2180/
  - assets/map/anholt_osmbright/12/2181/
  - assets/map/anholt_osmbright/13/4354/
  - assets/map/anholt_osmbright/13/4355/
  - assets/map/anholt_osmbright/13/4356/
  - assets/map/anholt_osmbright/13/4357/
  - assets/map/anholt_osmbright/13/4358/
  - assets/map/anholt_osmbright/13/4359/
  - assets/map/anholt_osmbright/13/4360/
  - assets/map/anholt_osmbright/13/4361/
  - assets/map/anholt_osmbright/13/4362/
  - assets/map/anholt_osmbright/13/4363/
  - assets/map/anholt_osmbright/14/8709/
  - assets/map/anholt_osmbright/14/8710/
  - assets/map/anholt_osmbright/14/8711/
  - assets/map/anholt_osmbright/14/8712/
  - assets/map/anholt_osmbright/14/8713/
  - assets/map/anholt_osmbright/14/8714/
  - assets/map/anholt_osmbright/14/8715/
  - assets/map/anholt_osmbright/14/8716/
  - assets/map/anholt_osmbright/14/8717/
  - assets/map/anholt_osmbright/14/8718/
  - assets/map/anholt_osmbright/14/8719/
  - assets/map/anholt_osmbright/14/8720/
  - assets/map/anholt_osmbright/14/8721/
  - assets/map/anholt_osmbright/14/8722/
  - assets/map/anholt_osmbright/14/8723/
  - assets/map/anholt_osmbright/14/8724/
  - assets/map/anholt_osmbright/14/8725/
  - assets/map/anholt_osmbright/14/8726/
  - assets/map/anholt_osmbright/14/8727/
  
