name: ambiante_mobile
description: A map gathering all events occuring in Namur.

# Required for release
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  flutter_map: ^0.7.3
  # Launch urls in other apps
  url_launcher: ^5.2.5

  http: 0.12.0+2
  # Additional material design icons
  mdi: ^0.2.0
  
# Required for development
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Command line tool used to set the app icon
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true
  assets:
  - assets/map/

